name: SerialLib-Builder

on:
  workflow_dispatch:

jobs:
  build:
    name: Build serial port lib
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm i
        working-directory: ./blp-serial
      - run: npm run build
        working-directory: ./blp-serial
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Serial LIB build for ${{ matrix.config.os }}
          file_pattern: /blp-serial/lib/bindings/native/*.node